# Generated by Django 3.2.3 on 2021-05-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
