# Generated by Django 3.2.3 on 2021-05-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0004_alter_todo_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='user_create',
        ),
    ]
